import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/provider/Providers";
import ChatPopup from "@/components/ChatPopup";

export const metadata: Metadata = {
  title: "Management Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <ChatPopup />
        </Providers>
      </body>
    </html>
  );
}
