import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/provider/Providers";

export const metadata: Metadata = {
    title: "Management Site",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
